
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project. We at hackStation provide a platform to share your work in number.
  Please adhere to our [Code of Conduct](https://github.com/ashishnagpal2498/hackstation/blob/master/CODE_OF_CONDUCT.md).ğŸ™Œ
  Kindly ensure you have fulfilled all the project guidelines.
  
  
  
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project. We at hackStation provide a platform to share your work in number.
  Please adhere to our [Code of Conduct](https://github.com/ashishnagpal2498/hackstation/blob/master/CODE_OF_CONDUCT.md).ğŸ™Œ
  Kindly ensure you have fulfilled all the project guidelines.
  
  
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€
